set_db port:ecc_engine/clk .original_name {clk}
set_db port:ecc_engine/rst_n .original_name {rst_n}
set_db port:ecc_engine/op_encode .original_name {op_encode}
set_db port:ecc_engine/op_decode .original_name {op_decode}
set_db port:ecc_engine/valid_in .original_name {valid_in}
set_db {port:ecc_engine/data_in[63]} .original_name {data_in[63]}
set_db {port:ecc_engine/data_in[62]} .original_name {data_in[62]}
set_db {port:ecc_engine/data_in[61]} .original_name {data_in[61]}
set_db {port:ecc_engine/data_in[60]} .original_name {data_in[60]}
set_db {port:ecc_engine/data_in[59]} .original_name {data_in[59]}
set_db {port:ecc_engine/data_in[58]} .original_name {data_in[58]}
set_db {port:ecc_engine/data_in[57]} .original_name {data_in[57]}
set_db {port:ecc_engine/data_in[56]} .original_name {data_in[56]}
set_db {port:ecc_engine/data_in[55]} .original_name {data_in[55]}
set_db {port:ecc_engine/data_in[54]} .original_name {data_in[54]}
set_db {port:ecc_engine/data_in[53]} .original_name {data_in[53]}
set_db {port:ecc_engine/data_in[52]} .original_name {data_in[52]}
set_db {port:ecc_engine/data_in[51]} .original_name {data_in[51]}
set_db {port:ecc_engine/data_in[50]} .original_name {data_in[50]}
set_db {port:ecc_engine/data_in[49]} .original_name {data_in[49]}
set_db {port:ecc_engine/data_in[48]} .original_name {data_in[48]}
set_db {port:ecc_engine/data_in[47]} .original_name {data_in[47]}
set_db {port:ecc_engine/data_in[46]} .original_name {data_in[46]}
set_db {port:ecc_engine/data_in[45]} .original_name {data_in[45]}
set_db {port:ecc_engine/data_in[44]} .original_name {data_in[44]}
set_db {port:ecc_engine/data_in[43]} .original_name {data_in[43]}
set_db {port:ecc_engine/data_in[42]} .original_name {data_in[42]}
set_db {port:ecc_engine/data_in[41]} .original_name {data_in[41]}
set_db {port:ecc_engine/data_in[40]} .original_name {data_in[40]}
set_db {port:ecc_engine/data_in[39]} .original_name {data_in[39]}
set_db {port:ecc_engine/data_in[38]} .original_name {data_in[38]}
set_db {port:ecc_engine/data_in[37]} .original_name {data_in[37]}
set_db {port:ecc_engine/data_in[36]} .original_name {data_in[36]}
set_db {port:ecc_engine/data_in[35]} .original_name {data_in[35]}
set_db {port:ecc_engine/data_in[34]} .original_name {data_in[34]}
set_db {port:ecc_engine/data_in[33]} .original_name {data_in[33]}
set_db {port:ecc_engine/data_in[32]} .original_name {data_in[32]}
set_db {port:ecc_engine/data_in[31]} .original_name {data_in[31]}
set_db {port:ecc_engine/data_in[30]} .original_name {data_in[30]}
set_db {port:ecc_engine/data_in[29]} .original_name {data_in[29]}
set_db {port:ecc_engine/data_in[28]} .original_name {data_in[28]}
set_db {port:ecc_engine/data_in[27]} .original_name {data_in[27]}
set_db {port:ecc_engine/data_in[26]} .original_name {data_in[26]}
set_db {port:ecc_engine/data_in[25]} .original_name {data_in[25]}
set_db {port:ecc_engine/data_in[24]} .original_name {data_in[24]}
set_db {port:ecc_engine/data_in[23]} .original_name {data_in[23]}
set_db {port:ecc_engine/data_in[22]} .original_name {data_in[22]}
set_db {port:ecc_engine/data_in[21]} .original_name {data_in[21]}
set_db {port:ecc_engine/data_in[20]} .original_name {data_in[20]}
set_db {port:ecc_engine/data_in[19]} .original_name {data_in[19]}
set_db {port:ecc_engine/data_in[18]} .original_name {data_in[18]}
set_db {port:ecc_engine/data_in[17]} .original_name {data_in[17]}
set_db {port:ecc_engine/data_in[16]} .original_name {data_in[16]}
set_db {port:ecc_engine/data_in[15]} .original_name {data_in[15]}
set_db {port:ecc_engine/data_in[14]} .original_name {data_in[14]}
set_db {port:ecc_engine/data_in[13]} .original_name {data_in[13]}
set_db {port:ecc_engine/data_in[12]} .original_name {data_in[12]}
set_db {port:ecc_engine/data_in[11]} .original_name {data_in[11]}
set_db {port:ecc_engine/data_in[10]} .original_name {data_in[10]}
set_db {port:ecc_engine/data_in[9]} .original_name {data_in[9]}
set_db {port:ecc_engine/data_in[8]} .original_name {data_in[8]}
set_db {port:ecc_engine/data_in[7]} .original_name {data_in[7]}
set_db {port:ecc_engine/data_in[6]} .original_name {data_in[6]}
set_db {port:ecc_engine/data_in[5]} .original_name {data_in[5]}
set_db {port:ecc_engine/data_in[4]} .original_name {data_in[4]}
set_db {port:ecc_engine/data_in[3]} .original_name {data_in[3]}
set_db {port:ecc_engine/data_in[2]} .original_name {data_in[2]}
set_db {port:ecc_engine/data_in[1]} .original_name {data_in[1]}
set_db {port:ecc_engine/data_in[0]} .original_name {data_in[0]}
set_db {port:ecc_engine/codeword_in[71]} .original_name {codeword_in[71]}
set_db {port:ecc_engine/codeword_in[70]} .original_name {codeword_in[70]}
set_db {port:ecc_engine/codeword_in[69]} .original_name {codeword_in[69]}
set_db {port:ecc_engine/codeword_in[68]} .original_name {codeword_in[68]}
set_db {port:ecc_engine/codeword_in[67]} .original_name {codeword_in[67]}
set_db {port:ecc_engine/codeword_in[66]} .original_name {codeword_in[66]}
set_db {port:ecc_engine/codeword_in[65]} .original_name {codeword_in[65]}
set_db {port:ecc_engine/codeword_in[64]} .original_name {codeword_in[64]}
set_db {port:ecc_engine/codeword_in[63]} .original_name {codeword_in[63]}
set_db {port:ecc_engine/codeword_in[62]} .original_name {codeword_in[62]}
set_db {port:ecc_engine/codeword_in[61]} .original_name {codeword_in[61]}
set_db {port:ecc_engine/codeword_in[60]} .original_name {codeword_in[60]}
set_db {port:ecc_engine/codeword_in[59]} .original_name {codeword_in[59]}
set_db {port:ecc_engine/codeword_in[58]} .original_name {codeword_in[58]}
set_db {port:ecc_engine/codeword_in[57]} .original_name {codeword_in[57]}
set_db {port:ecc_engine/codeword_in[56]} .original_name {codeword_in[56]}
set_db {port:ecc_engine/codeword_in[55]} .original_name {codeword_in[55]}
set_db {port:ecc_engine/codeword_in[54]} .original_name {codeword_in[54]}
set_db {port:ecc_engine/codeword_in[53]} .original_name {codeword_in[53]}
set_db {port:ecc_engine/codeword_in[52]} .original_name {codeword_in[52]}
set_db {port:ecc_engine/codeword_in[51]} .original_name {codeword_in[51]}
set_db {port:ecc_engine/codeword_in[50]} .original_name {codeword_in[50]}
set_db {port:ecc_engine/codeword_in[49]} .original_name {codeword_in[49]}
set_db {port:ecc_engine/codeword_in[48]} .original_name {codeword_in[48]}
set_db {port:ecc_engine/codeword_in[47]} .original_name {codeword_in[47]}
set_db {port:ecc_engine/codeword_in[46]} .original_name {codeword_in[46]}
set_db {port:ecc_engine/codeword_in[45]} .original_name {codeword_in[45]}
set_db {port:ecc_engine/codeword_in[44]} .original_name {codeword_in[44]}
set_db {port:ecc_engine/codeword_in[43]} .original_name {codeword_in[43]}
set_db {port:ecc_engine/codeword_in[42]} .original_name {codeword_in[42]}
set_db {port:ecc_engine/codeword_in[41]} .original_name {codeword_in[41]}
set_db {port:ecc_engine/codeword_in[40]} .original_name {codeword_in[40]}
set_db {port:ecc_engine/codeword_in[39]} .original_name {codeword_in[39]}
set_db {port:ecc_engine/codeword_in[38]} .original_name {codeword_in[38]}
set_db {port:ecc_engine/codeword_in[37]} .original_name {codeword_in[37]}
set_db {port:ecc_engine/codeword_in[36]} .original_name {codeword_in[36]}
set_db {port:ecc_engine/codeword_in[35]} .original_name {codeword_in[35]}
set_db {port:ecc_engine/codeword_in[34]} .original_name {codeword_in[34]}
set_db {port:ecc_engine/codeword_in[33]} .original_name {codeword_in[33]}
set_db {port:ecc_engine/codeword_in[32]} .original_name {codeword_in[32]}
set_db {port:ecc_engine/codeword_in[31]} .original_name {codeword_in[31]}
set_db {port:ecc_engine/codeword_in[30]} .original_name {codeword_in[30]}
set_db {port:ecc_engine/codeword_in[29]} .original_name {codeword_in[29]}
set_db {port:ecc_engine/codeword_in[28]} .original_name {codeword_in[28]}
set_db {port:ecc_engine/codeword_in[27]} .original_name {codeword_in[27]}
set_db {port:ecc_engine/codeword_in[26]} .original_name {codeword_in[26]}
set_db {port:ecc_engine/codeword_in[25]} .original_name {codeword_in[25]}
set_db {port:ecc_engine/codeword_in[24]} .original_name {codeword_in[24]}
set_db {port:ecc_engine/codeword_in[23]} .original_name {codeword_in[23]}
set_db {port:ecc_engine/codeword_in[22]} .original_name {codeword_in[22]}
set_db {port:ecc_engine/codeword_in[21]} .original_name {codeword_in[21]}
set_db {port:ecc_engine/codeword_in[20]} .original_name {codeword_in[20]}
set_db {port:ecc_engine/codeword_in[19]} .original_name {codeword_in[19]}
set_db {port:ecc_engine/codeword_in[18]} .original_name {codeword_in[18]}
set_db {port:ecc_engine/codeword_in[17]} .original_name {codeword_in[17]}
set_db {port:ecc_engine/codeword_in[16]} .original_name {codeword_in[16]}
set_db {port:ecc_engine/codeword_in[15]} .original_name {codeword_in[15]}
set_db {port:ecc_engine/codeword_in[14]} .original_name {codeword_in[14]}
set_db {port:ecc_engine/codeword_in[13]} .original_name {codeword_in[13]}
set_db {port:ecc_engine/codeword_in[12]} .original_name {codeword_in[12]}
set_db {port:ecc_engine/codeword_in[11]} .original_name {codeword_in[11]}
set_db {port:ecc_engine/codeword_in[10]} .original_name {codeword_in[10]}
set_db {port:ecc_engine/codeword_in[9]} .original_name {codeword_in[9]}
set_db {port:ecc_engine/codeword_in[8]} .original_name {codeword_in[8]}
set_db {port:ecc_engine/codeword_in[7]} .original_name {codeword_in[7]}
set_db {port:ecc_engine/codeword_in[6]} .original_name {codeword_in[6]}
set_db {port:ecc_engine/codeword_in[5]} .original_name {codeword_in[5]}
set_db {port:ecc_engine/codeword_in[4]} .original_name {codeword_in[4]}
set_db {port:ecc_engine/codeword_in[3]} .original_name {codeword_in[3]}
set_db {port:ecc_engine/codeword_in[2]} .original_name {codeword_in[2]}
set_db {port:ecc_engine/codeword_in[1]} .original_name {codeword_in[1]}
set_db {port:ecc_engine/codeword_in[0]} .original_name {codeword_in[0]}
set_db {port:ecc_engine/codeword_out[71]} .original_name {codeword_out[71]}
set_db {port:ecc_engine/codeword_out[70]} .original_name {codeword_out[70]}
set_db {port:ecc_engine/codeword_out[69]} .original_name {codeword_out[69]}
set_db {port:ecc_engine/codeword_out[68]} .original_name {codeword_out[68]}
set_db {port:ecc_engine/codeword_out[67]} .original_name {codeword_out[67]}
set_db {port:ecc_engine/codeword_out[66]} .original_name {codeword_out[66]}
set_db {port:ecc_engine/codeword_out[65]} .original_name {codeword_out[65]}
set_db {port:ecc_engine/codeword_out[64]} .original_name {codeword_out[64]}
set_db {port:ecc_engine/codeword_out[63]} .original_name {codeword_out[63]}
set_db {port:ecc_engine/codeword_out[62]} .original_name {codeword_out[62]}
set_db {port:ecc_engine/codeword_out[61]} .original_name {codeword_out[61]}
set_db {port:ecc_engine/codeword_out[60]} .original_name {codeword_out[60]}
set_db {port:ecc_engine/codeword_out[59]} .original_name {codeword_out[59]}
set_db {port:ecc_engine/codeword_out[58]} .original_name {codeword_out[58]}
set_db {port:ecc_engine/codeword_out[57]} .original_name {codeword_out[57]}
set_db {port:ecc_engine/codeword_out[56]} .original_name {codeword_out[56]}
set_db {port:ecc_engine/codeword_out[55]} .original_name {codeword_out[55]}
set_db {port:ecc_engine/codeword_out[54]} .original_name {codeword_out[54]}
set_db {port:ecc_engine/codeword_out[53]} .original_name {codeword_out[53]}
set_db {port:ecc_engine/codeword_out[52]} .original_name {codeword_out[52]}
set_db {port:ecc_engine/codeword_out[51]} .original_name {codeword_out[51]}
set_db {port:ecc_engine/codeword_out[50]} .original_name {codeword_out[50]}
set_db {port:ecc_engine/codeword_out[49]} .original_name {codeword_out[49]}
set_db {port:ecc_engine/codeword_out[48]} .original_name {codeword_out[48]}
set_db {port:ecc_engine/codeword_out[47]} .original_name {codeword_out[47]}
set_db {port:ecc_engine/codeword_out[46]} .original_name {codeword_out[46]}
set_db {port:ecc_engine/codeword_out[45]} .original_name {codeword_out[45]}
set_db {port:ecc_engine/codeword_out[44]} .original_name {codeword_out[44]}
set_db {port:ecc_engine/codeword_out[43]} .original_name {codeword_out[43]}
set_db {port:ecc_engine/codeword_out[42]} .original_name {codeword_out[42]}
set_db {port:ecc_engine/codeword_out[41]} .original_name {codeword_out[41]}
set_db {port:ecc_engine/codeword_out[40]} .original_name {codeword_out[40]}
set_db {port:ecc_engine/codeword_out[39]} .original_name {codeword_out[39]}
set_db {port:ecc_engine/codeword_out[38]} .original_name {codeword_out[38]}
set_db {port:ecc_engine/codeword_out[37]} .original_name {codeword_out[37]}
set_db {port:ecc_engine/codeword_out[36]} .original_name {codeword_out[36]}
set_db {port:ecc_engine/codeword_out[35]} .original_name {codeword_out[35]}
set_db {port:ecc_engine/codeword_out[34]} .original_name {codeword_out[34]}
set_db {port:ecc_engine/codeword_out[33]} .original_name {codeword_out[33]}
set_db {port:ecc_engine/codeword_out[32]} .original_name {codeword_out[32]}
set_db {port:ecc_engine/codeword_out[31]} .original_name {codeword_out[31]}
set_db {port:ecc_engine/codeword_out[30]} .original_name {codeword_out[30]}
set_db {port:ecc_engine/codeword_out[29]} .original_name {codeword_out[29]}
set_db {port:ecc_engine/codeword_out[28]} .original_name {codeword_out[28]}
set_db {port:ecc_engine/codeword_out[27]} .original_name {codeword_out[27]}
set_db {port:ecc_engine/codeword_out[26]} .original_name {codeword_out[26]}
set_db {port:ecc_engine/codeword_out[25]} .original_name {codeword_out[25]}
set_db {port:ecc_engine/codeword_out[24]} .original_name {codeword_out[24]}
set_db {port:ecc_engine/codeword_out[23]} .original_name {codeword_out[23]}
set_db {port:ecc_engine/codeword_out[22]} .original_name {codeword_out[22]}
set_db {port:ecc_engine/codeword_out[21]} .original_name {codeword_out[21]}
set_db {port:ecc_engine/codeword_out[20]} .original_name {codeword_out[20]}
set_db {port:ecc_engine/codeword_out[19]} .original_name {codeword_out[19]}
set_db {port:ecc_engine/codeword_out[18]} .original_name {codeword_out[18]}
set_db {port:ecc_engine/codeword_out[17]} .original_name {codeword_out[17]}
set_db {port:ecc_engine/codeword_out[16]} .original_name {codeword_out[16]}
set_db {port:ecc_engine/codeword_out[15]} .original_name {codeword_out[15]}
set_db {port:ecc_engine/codeword_out[14]} .original_name {codeword_out[14]}
set_db {port:ecc_engine/codeword_out[13]} .original_name {codeword_out[13]}
set_db {port:ecc_engine/codeword_out[12]} .original_name {codeword_out[12]}
set_db {port:ecc_engine/codeword_out[11]} .original_name {codeword_out[11]}
set_db {port:ecc_engine/codeword_out[10]} .original_name {codeword_out[10]}
set_db {port:ecc_engine/codeword_out[9]} .original_name {codeword_out[9]}
set_db {port:ecc_engine/codeword_out[8]} .original_name {codeword_out[8]}
set_db {port:ecc_engine/codeword_out[7]} .original_name {codeword_out[7]}
set_db {port:ecc_engine/codeword_out[6]} .original_name {codeword_out[6]}
set_db {port:ecc_engine/codeword_out[5]} .original_name {codeword_out[5]}
set_db {port:ecc_engine/codeword_out[4]} .original_name {codeword_out[4]}
set_db {port:ecc_engine/codeword_out[3]} .original_name {codeword_out[3]}
set_db {port:ecc_engine/codeword_out[2]} .original_name {codeword_out[2]}
set_db {port:ecc_engine/codeword_out[1]} .original_name {codeword_out[1]}
set_db {port:ecc_engine/codeword_out[0]} .original_name {codeword_out[0]}
set_db {port:ecc_engine/data_out[63]} .original_name {data_out[63]}
set_db {port:ecc_engine/data_out[62]} .original_name {data_out[62]}
set_db {port:ecc_engine/data_out[61]} .original_name {data_out[61]}
set_db {port:ecc_engine/data_out[60]} .original_name {data_out[60]}
set_db {port:ecc_engine/data_out[59]} .original_name {data_out[59]}
set_db {port:ecc_engine/data_out[58]} .original_name {data_out[58]}
set_db {port:ecc_engine/data_out[57]} .original_name {data_out[57]}
set_db {port:ecc_engine/data_out[56]} .original_name {data_out[56]}
set_db {port:ecc_engine/data_out[55]} .original_name {data_out[55]}
set_db {port:ecc_engine/data_out[54]} .original_name {data_out[54]}
set_db {port:ecc_engine/data_out[53]} .original_name {data_out[53]}
set_db {port:ecc_engine/data_out[52]} .original_name {data_out[52]}
set_db {port:ecc_engine/data_out[51]} .original_name {data_out[51]}
set_db {port:ecc_engine/data_out[50]} .original_name {data_out[50]}
set_db {port:ecc_engine/data_out[49]} .original_name {data_out[49]}
set_db {port:ecc_engine/data_out[48]} .original_name {data_out[48]}
set_db {port:ecc_engine/data_out[47]} .original_name {data_out[47]}
set_db {port:ecc_engine/data_out[46]} .original_name {data_out[46]}
set_db {port:ecc_engine/data_out[45]} .original_name {data_out[45]}
set_db {port:ecc_engine/data_out[44]} .original_name {data_out[44]}
set_db {port:ecc_engine/data_out[43]} .original_name {data_out[43]}
set_db {port:ecc_engine/data_out[42]} .original_name {data_out[42]}
set_db {port:ecc_engine/data_out[41]} .original_name {data_out[41]}
set_db {port:ecc_engine/data_out[40]} .original_name {data_out[40]}
set_db {port:ecc_engine/data_out[39]} .original_name {data_out[39]}
set_db {port:ecc_engine/data_out[38]} .original_name {data_out[38]}
set_db {port:ecc_engine/data_out[37]} .original_name {data_out[37]}
set_db {port:ecc_engine/data_out[36]} .original_name {data_out[36]}
set_db {port:ecc_engine/data_out[35]} .original_name {data_out[35]}
set_db {port:ecc_engine/data_out[34]} .original_name {data_out[34]}
set_db {port:ecc_engine/data_out[33]} .original_name {data_out[33]}
set_db {port:ecc_engine/data_out[32]} .original_name {data_out[32]}
set_db {port:ecc_engine/data_out[31]} .original_name {data_out[31]}
set_db {port:ecc_engine/data_out[30]} .original_name {data_out[30]}
set_db {port:ecc_engine/data_out[29]} .original_name {data_out[29]}
set_db {port:ecc_engine/data_out[28]} .original_name {data_out[28]}
set_db {port:ecc_engine/data_out[27]} .original_name {data_out[27]}
set_db {port:ecc_engine/data_out[26]} .original_name {data_out[26]}
set_db {port:ecc_engine/data_out[25]} .original_name {data_out[25]}
set_db {port:ecc_engine/data_out[24]} .original_name {data_out[24]}
set_db {port:ecc_engine/data_out[23]} .original_name {data_out[23]}
set_db {port:ecc_engine/data_out[22]} .original_name {data_out[22]}
set_db {port:ecc_engine/data_out[21]} .original_name {data_out[21]}
set_db {port:ecc_engine/data_out[20]} .original_name {data_out[20]}
set_db {port:ecc_engine/data_out[19]} .original_name {data_out[19]}
set_db {port:ecc_engine/data_out[18]} .original_name {data_out[18]}
set_db {port:ecc_engine/data_out[17]} .original_name {data_out[17]}
set_db {port:ecc_engine/data_out[16]} .original_name {data_out[16]}
set_db {port:ecc_engine/data_out[15]} .original_name {data_out[15]}
set_db {port:ecc_engine/data_out[14]} .original_name {data_out[14]}
set_db {port:ecc_engine/data_out[13]} .original_name {data_out[13]}
set_db {port:ecc_engine/data_out[12]} .original_name {data_out[12]}
set_db {port:ecc_engine/data_out[11]} .original_name {data_out[11]}
set_db {port:ecc_engine/data_out[10]} .original_name {data_out[10]}
set_db {port:ecc_engine/data_out[9]} .original_name {data_out[9]}
set_db {port:ecc_engine/data_out[8]} .original_name {data_out[8]}
set_db {port:ecc_engine/data_out[7]} .original_name {data_out[7]}
set_db {port:ecc_engine/data_out[6]} .original_name {data_out[6]}
set_db {port:ecc_engine/data_out[5]} .original_name {data_out[5]}
set_db {port:ecc_engine/data_out[4]} .original_name {data_out[4]}
set_db {port:ecc_engine/data_out[3]} .original_name {data_out[3]}
set_db {port:ecc_engine/data_out[2]} .original_name {data_out[2]}
set_db {port:ecc_engine/data_out[1]} .original_name {data_out[1]}
set_db {port:ecc_engine/data_out[0]} .original_name {data_out[0]}
set_db port:ecc_engine/ecc_corrected .original_name {ecc_corrected}
set_db port:ecc_engine/ecc_uncorrectable .original_name {ecc_uncorrectable}
set_db port:ecc_engine/valid_out .original_name {valid_out}



set_db {pin:ecc_engine/data_out_reg[41]/Q} .original_name {data_out[41]/q}
set_db {pin:ecc_engine/data_out_reg[45]/Q} .original_name {data_out[45]/q}
set_db {pin:ecc_engine/data_out_reg[40]/Q} .original_name {data_out[40]/q}
set_db {pin:ecc_engine/data_out_reg[42]/Q} .original_name {data_out[42]/q}
set_db {pin:ecc_engine/data_out_reg[46]/Q} .original_name {data_out[46]/q}
set_db {pin:ecc_engine/data_out_reg[44]/Q} .original_name {data_out[44]/q}
set_db {pin:ecc_engine/data_out_reg[43]/Q} .original_name {data_out[43]/q}
set_db {pin:ecc_engine/data_out_reg[47]/Q} .original_name {data_out[47]/q}
set_db {pin:ecc_engine/data_out_reg[9]/Q} .original_name {data_out[9]/q}
set_db {pin:ecc_engine/data_out_reg[11]/Q} .original_name {data_out[11]/q}
set_db {pin:ecc_engine/data_out_reg[12]/Q} .original_name {data_out[12]/q}
set_db {pin:ecc_engine/data_out_reg[13]/Q} .original_name {data_out[13]/q}
set_db {pin:ecc_engine/data_out_reg[29]/Q} .original_name {data_out[29]/q}
set_db {pin:ecc_engine/data_out_reg[15]/Q} .original_name {data_out[15]/q}
set_db {pin:ecc_engine/data_out_reg[10]/Q} .original_name {data_out[10]/q}
set_db {pin:ecc_engine/data_out_reg[27]/Q} .original_name {data_out[27]/q}
set_db {pin:ecc_engine/data_out_reg[26]/Q} .original_name {data_out[26]/q}
set_db {pin:ecc_engine/data_out_reg[25]/Q} .original_name {data_out[25]/q}
set_db {pin:ecc_engine/data_out_reg[28]/Q} .original_name {data_out[28]/q}
set_db {pin:ecc_engine/data_out_reg[24]/Q} .original_name {data_out[24]/q}
set_db {pin:ecc_engine/data_out_reg[14]/Q} .original_name {data_out[14]/q}
set_db {pin:ecc_engine/data_out_reg[30]/Q} .original_name {data_out[30]/q}
set_db {pin:ecc_engine/data_out_reg[31]/Q} .original_name {data_out[31]/q}
set_db {pin:ecc_engine/data_out_reg[16]/Q} .original_name {data_out[16]/q}
set_db {pin:ecc_engine/data_out_reg[48]/Q} .original_name {data_out[48]/q}
set_db {pin:ecc_engine/data_out_reg[3]/Q} .original_name {data_out[3]/q}
set_db {pin:ecc_engine/data_out_reg[6]/Q} .original_name {data_out[6]/q}
set_db {pin:ecc_engine/data_out_reg[1]/Q} .original_name {data_out[1]/q}
set_db {pin:ecc_engine/data_out_reg[54]/Q} .original_name {data_out[54]/q}
set_db {pin:ecc_engine/data_out_reg[0]/Q} .original_name {data_out[0]/q}
set_db {pin:ecc_engine/data_out_reg[7]/Q} .original_name {data_out[7]/q}
set_db {pin:ecc_engine/data_out_reg[8]/Q} .original_name {data_out[8]/q}
set_db {pin:ecc_engine/data_out_reg[4]/Q} .original_name {data_out[4]/q}
set_db {pin:ecc_engine/data_out_reg[5]/Q} .original_name {data_out[5]/q}
set_db {pin:ecc_engine/data_out_reg[17]/Q} .original_name {data_out[17]/q}
set_db {pin:ecc_engine/data_out_reg[19]/Q} .original_name {data_out[19]/q}
set_db {pin:ecc_engine/data_out_reg[20]/Q} .original_name {data_out[20]/q}
set_db {pin:ecc_engine/data_out_reg[21]/Q} .original_name {data_out[21]/q}
set_db {pin:ecc_engine/data_out_reg[22]/Q} .original_name {data_out[22]/q}
set_db {pin:ecc_engine/data_out_reg[23]/Q} .original_name {data_out[23]/q}
set_db {pin:ecc_engine/data_out_reg[2]/Q} .original_name {data_out[2]/q}
set_db {pin:ecc_engine/data_out_reg[36]/Q} .original_name {data_out[36]/q}
set_db {pin:ecc_engine/data_out_reg[37]/Q} .original_name {data_out[37]/q}
set_db {pin:ecc_engine/data_out_reg[38]/Q} .original_name {data_out[38]/q}
set_db {pin:ecc_engine/data_out_reg[35]/Q} .original_name {data_out[35]/q}
set_db {pin:ecc_engine/data_out_reg[33]/Q} .original_name {data_out[33]/q}
set_db {pin:ecc_engine/data_out_reg[39]/Q} .original_name {data_out[39]/q}
set_db {pin:ecc_engine/data_out_reg[32]/Q} .original_name {data_out[32]/q}
set_db {pin:ecc_engine/data_out_reg[34]/Q} .original_name {data_out[34]/q}
set_db {pin:ecc_engine/data_out_reg[18]/Q} .original_name {data_out[18]/q}
set_db {pin:ecc_engine/data_out_reg[49]/Q} .original_name {data_out[49]/q}
set_db {pin:ecc_engine/data_out_reg[51]/Q} .original_name {data_out[51]/q}
set_db {pin:ecc_engine/data_out_reg[52]/Q} .original_name {data_out[52]/q}
set_db {pin:ecc_engine/data_out_reg[53]/Q} .original_name {data_out[53]/q}
set_db {pin:ecc_engine/data_out_reg[55]/Q} .original_name {data_out[55]/q}
set_db {pin:ecc_engine/data_out_reg[50]/Q} .original_name {data_out[50]/q}
set_db {pin:ecc_engine/data_out_reg[59]/Q} .original_name {data_out[59]/q}
set_db {pin:ecc_engine/data_out_reg[58]/Q} .original_name {data_out[58]/q}
set_db {pin:ecc_engine/data_out_reg[62]/Q} .original_name {data_out[62]/q}
set_db {pin:ecc_engine/data_out_reg[61]/Q} .original_name {data_out[61]/q}
set_db {pin:ecc_engine/data_out_reg[57]/Q} .original_name {data_out[57]/q}
set_db {pin:ecc_engine/data_out_reg[63]/Q} .original_name {data_out[63]/q}
set_db {pin:ecc_engine/data_out_reg[60]/Q} .original_name {data_out[60]/q}
set_db {pin:ecc_engine/codeword_out_reg[7]/Q} .original_name {codeword_out[7]/q}
set_db {pin:ecc_engine/data_out_reg[56]/Q} .original_name {data_out[56]/q}
set_db {pin:ecc_engine/s1_parity_reg[7]/Q} .original_name {s1_parity[7]/q}
set_db pin:ecc_engine/ecc_corrected_reg/Q .original_name {ecc_corrected/q}
set_db pin:ecc_engine/ecc_uncorrectable_reg/Q .original_name {ecc_uncorrectable/q}
set_db {pin:ecc_engine/codeword_out_reg[2]/Q} .original_name {codeword_out[2]/q}
set_db {pin:ecc_engine/codeword_out_reg[0]/Q} .original_name {codeword_out[0]/q}
set_db {pin:ecc_engine/codeword_out_reg[1]/Q} .original_name {codeword_out[1]/q}
set_db {pin:ecc_engine/codeword_out_reg[5]/Q} .original_name {codeword_out[5]/q}
set_db {pin:ecc_engine/s1_parity_reg[2]/Q} .original_name {s1_parity[2]/q}
set_db {pin:ecc_engine/s1_parity_reg[0]/Q} .original_name {s1_parity[0]/q}
set_db {pin:ecc_engine/codeword_out_reg[3]/Q} .original_name {codeword_out[3]/q}
set_db {pin:ecc_engine/s1_parity_reg[1]/Q} .original_name {s1_parity[1]/q}
set_db {pin:ecc_engine/codeword_out_reg[4]/Q} .original_name {codeword_out[4]/q}
set_db {pin:ecc_engine/s1_parity_reg[5]/Q} .original_name {s1_parity[5]/q}
set_db {pin:ecc_engine/s1_parity_reg[3]/Q} .original_name {s1_parity[3]/q}
set_db {pin:ecc_engine/s1_parity_reg[4]/Q} .original_name {s1_parity[4]/q}
set_db {pin:ecc_engine/codeword_out_reg[6]/Q} .original_name {codeword_out[6]/q}
set_db {pin:ecc_engine/s1_parity_reg[6]/Q} .original_name {s1_parity[6]/q}
set_db {pin:ecc_engine/codeword_out_reg[60]/Q} .original_name {codeword_out[60]/q}
set_db {pin:ecc_engine/codeword_out_reg[18]/Q} .original_name {codeword_out[18]/q}
set_db {pin:ecc_engine/codeword_out_reg[26]/Q} .original_name {codeword_out[26]/q}
set_db {pin:ecc_engine/codeword_out_reg[59]/Q} .original_name {codeword_out[59]/q}
set_db {pin:ecc_engine/codeword_out_reg[43]/Q} .original_name {codeword_out[43]/q}
set_db {pin:ecc_engine/codeword_out_reg[20]/Q} .original_name {codeword_out[20]/q}
set_db {pin:ecc_engine/codeword_out_reg[24]/Q} .original_name {codeword_out[24]/q}
set_db {pin:ecc_engine/codeword_out_reg[29]/Q} .original_name {codeword_out[29]/q}
set_db {pin:ecc_engine/codeword_out_reg[50]/Q} .original_name {codeword_out[50]/q}
set_db {pin:ecc_engine/codeword_out_reg[58]/Q} .original_name {codeword_out[58]/q}
set_db {pin:ecc_engine/codeword_out_reg[14]/Q} .original_name {codeword_out[14]/q}
set_db {pin:ecc_engine/codeword_out_reg[45]/Q} .original_name {codeword_out[45]/q}
set_db {pin:ecc_engine/codeword_out_reg[38]/Q} .original_name {codeword_out[38]/q}
set_db {pin:ecc_engine/codeword_out_reg[61]/Q} .original_name {codeword_out[61]/q}
set_db {pin:ecc_engine/codeword_out_reg[15]/Q} .original_name {codeword_out[15]/q}
set_db {pin:ecc_engine/codeword_out_reg[8]/Q} .original_name {codeword_out[8]/q}
set_db {pin:ecc_engine/codeword_out_reg[54]/Q} .original_name {codeword_out[54]/q}
set_db {pin:ecc_engine/codeword_out_reg[63]/Q} .original_name {codeword_out[63]/q}
set_db {pin:ecc_engine/codeword_out_reg[9]/Q} .original_name {codeword_out[9]/q}
set_db {pin:ecc_engine/codeword_out_reg[36]/Q} .original_name {codeword_out[36]/q}
set_db {pin:ecc_engine/codeword_out_reg[11]/Q} .original_name {codeword_out[11]/q}
set_db {pin:ecc_engine/codeword_out_reg[35]/Q} .original_name {codeword_out[35]/q}
set_db {pin:ecc_engine/codeword_out_reg[40]/Q} .original_name {codeword_out[40]/q}
set_db {pin:ecc_engine/codeword_out_reg[70]/Q} .original_name {codeword_out[70]/q}
set_db {pin:ecc_engine/codeword_out_reg[53]/Q} .original_name {codeword_out[53]/q}
set_db {pin:ecc_engine/codeword_out_reg[22]/Q} .original_name {codeword_out[22]/q}
set_db {pin:ecc_engine/codeword_out_reg[31]/Q} .original_name {codeword_out[31]/q}
set_db {pin:ecc_engine/codeword_out_reg[56]/Q} .original_name {codeword_out[56]/q}
set_db {pin:ecc_engine/codeword_out_reg[55]/Q} .original_name {codeword_out[55]/q}
set_db {pin:ecc_engine/codeword_out_reg[44]/Q} .original_name {codeword_out[44]/q}
set_db {pin:ecc_engine/codeword_out_reg[33]/Q} .original_name {codeword_out[33]/q}
set_db {pin:ecc_engine/codeword_out_reg[47]/Q} .original_name {codeword_out[47]/q}
set_db {pin:ecc_engine/codeword_out_reg[49]/Q} .original_name {codeword_out[49]/q}
set_db {pin:ecc_engine/codeword_out_reg[51]/Q} .original_name {codeword_out[51]/q}
set_db {pin:ecc_engine/codeword_out_reg[52]/Q} .original_name {codeword_out[52]/q}
set_db {pin:ecc_engine/codeword_out_reg[57]/Q} .original_name {codeword_out[57]/q}
set_db {pin:ecc_engine/codeword_out_reg[62]/Q} .original_name {codeword_out[62]/q}
set_db {pin:ecc_engine/codeword_out_reg[66]/Q} .original_name {codeword_out[66]/q}
set_db {pin:ecc_engine/codeword_out_reg[69]/Q} .original_name {codeword_out[69]/q}
set_db {pin:ecc_engine/codeword_out_reg[71]/Q} .original_name {codeword_out[71]/q}
set_db {pin:ecc_engine/codeword_out_reg[10]/Q} .original_name {codeword_out[10]/q}
set_db {pin:ecc_engine/codeword_out_reg[12]/Q} .original_name {codeword_out[12]/q}
set_db {pin:ecc_engine/codeword_out_reg[13]/Q} .original_name {codeword_out[13]/q}
set_db {pin:ecc_engine/codeword_out_reg[68]/Q} .original_name {codeword_out[68]/q}
set_db {pin:ecc_engine/codeword_out_reg[16]/Q} .original_name {codeword_out[16]/q}
set_db {pin:ecc_engine/codeword_out_reg[64]/Q} .original_name {codeword_out[64]/q}
set_db {pin:ecc_engine/codeword_out_reg[46]/Q} .original_name {codeword_out[46]/q}
set_db {pin:ecc_engine/codeword_out_reg[19]/Q} .original_name {codeword_out[19]/q}
set_db {pin:ecc_engine/codeword_out_reg[65]/Q} .original_name {codeword_out[65]/q}
set_db {pin:ecc_engine/codeword_out_reg[21]/Q} .original_name {codeword_out[21]/q}
set_db {pin:ecc_engine/codeword_out_reg[23]/Q} .original_name {codeword_out[23]/q}
set_db {pin:ecc_engine/codeword_out_reg[25]/Q} .original_name {codeword_out[25]/q}
set_db {pin:ecc_engine/codeword_out_reg[67]/Q} .original_name {codeword_out[67]/q}
set_db {pin:ecc_engine/codeword_out_reg[27]/Q} .original_name {codeword_out[27]/q}
set_db {pin:ecc_engine/codeword_out_reg[28]/Q} .original_name {codeword_out[28]/q}
set_db {pin:ecc_engine/codeword_out_reg[30]/Q} .original_name {codeword_out[30]/q}
set_db {pin:ecc_engine/codeword_out_reg[32]/Q} .original_name {codeword_out[32]/q}
set_db {pin:ecc_engine/codeword_out_reg[34]/Q} .original_name {codeword_out[34]/q}
set_db {pin:ecc_engine/codeword_out_reg[41]/Q} .original_name {codeword_out[41]/q}
set_db {pin:ecc_engine/codeword_out_reg[37]/Q} .original_name {codeword_out[37]/q}
set_db {pin:ecc_engine/codeword_out_reg[39]/Q} .original_name {codeword_out[39]/q}
set_db {pin:ecc_engine/codeword_out_reg[42]/Q} .original_name {codeword_out[42]/q}
set_db {pin:ecc_engine/codeword_out_reg[17]/Q} .original_name {codeword_out[17]/q}
set_db {pin:ecc_engine/codeword_out_reg[48]/Q} .original_name {codeword_out[48]/q}
set_db pin:ecc_engine/s1_decode_reg/Q .original_name {s1_decode/q}
set_db pin:ecc_engine/s1_encode_reg/Q .original_name {s1_encode/q}
set_db {pin:ecc_engine/s1_data_reg[48]/Q} .original_name {s1_data[48]/q}
set_db pin:ecc_engine/valid_out_reg/Q .original_name {valid_out/q}
set_db {pin:ecc_engine/s1_data_reg[40]/Q} .original_name {s1_data[40]/q}
set_db {pin:ecc_engine/s1_data_reg[43]/Q} .original_name {s1_data[43]/q}
set_db {pin:ecc_engine/s1_data_reg[6]/Q} .original_name {s1_data[6]/q}
set_db {pin:ecc_engine/s1_data_reg[25]/Q} .original_name {s1_data[25]/q}
set_db {pin:ecc_engine/s1_data_reg[14]/Q} .original_name {s1_data[14]/q}
set_db {pin:ecc_engine/s1_data_reg[54]/Q} .original_name {s1_data[54]/q}
set_db {pin:ecc_engine/s1_data_reg[34]/Q} .original_name {s1_data[34]/q}
set_db {pin:ecc_engine/s1_data_reg[23]/Q} .original_name {s1_data[23]/q}
set_db {pin:ecc_engine/s1_data_reg[46]/Q} .original_name {s1_data[46]/q}
set_db {pin:ecc_engine/s1_data_reg[41]/Q} .original_name {s1_data[41]/q}
set_db {pin:ecc_engine/s1_data_reg[11]/Q} .original_name {s1_data[11]/q}
set_db {pin:ecc_engine/s1_data_reg[53]/Q} .original_name {s1_data[53]/q}
set_db {pin:ecc_engine/s1_data_reg[2]/Q} .original_name {s1_data[2]/q}
set_db {pin:ecc_engine/s1_data_reg[19]/Q} .original_name {s1_data[19]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[53]/Q} .original_name {s1_codeword_in[53]/q}
set_db {pin:ecc_engine/s1_data_reg[57]/Q} .original_name {s1_data[57]/q}
set_db {pin:ecc_engine/s1_data_reg[32]/Q} .original_name {s1_data[32]/q}
set_db {pin:ecc_engine/s1_data_reg[10]/Q} .original_name {s1_data[10]/q}
set_db {pin:ecc_engine/s1_data_reg[42]/Q} .original_name {s1_data[42]/q}
set_db {pin:ecc_engine/s1_data_reg[63]/Q} .original_name {s1_data[63]/q}
set_db {pin:ecc_engine/s1_data_reg[56]/Q} .original_name {s1_data[56]/q}
set_db {pin:ecc_engine/s1_data_reg[30]/Q} .original_name {s1_data[30]/q}
set_db {pin:ecc_engine/s1_data_reg[18]/Q} .original_name {s1_data[18]/q}
set_db {pin:ecc_engine/s1_data_reg[24]/Q} .original_name {s1_data[24]/q}
set_db {pin:ecc_engine/s1_data_reg[36]/Q} .original_name {s1_data[36]/q}
set_db {pin:ecc_engine/s1_data_reg[9]/Q} .original_name {s1_data[9]/q}
set_db {pin:ecc_engine/s1_data_reg[22]/Q} .original_name {s1_data[22]/q}
set_db {pin:ecc_engine/s1_data_reg[37]/Q} .original_name {s1_data[37]/q}
set_db {pin:ecc_engine/s1_data_reg[58]/Q} .original_name {s1_data[58]/q}
set_db {pin:ecc_engine/s1_data_reg[16]/Q} .original_name {s1_data[16]/q}
set_db {pin:ecc_engine/s1_data_reg[17]/Q} .original_name {s1_data[17]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[56]/Q} .original_name {s1_codeword_in[56]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[6]/Q} .original_name {s1_codeword_in[6]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[9]/Q} .original_name {s1_codeword_in[9]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[49]/Q} .original_name {s1_codeword_in[49]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[0]/Q} .original_name {s1_codeword_in[0]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[33]/Q} .original_name {s1_codeword_in[33]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[41]/Q} .original_name {s1_codeword_in[41]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[1]/Q} .original_name {s1_codeword_in[1]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[19]/Q} .original_name {s1_codeword_in[19]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[17]/Q} .original_name {s1_codeword_in[17]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[3]/Q} .original_name {s1_codeword_in[3]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[28]/Q} .original_name {s1_codeword_in[28]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[42]/Q} .original_name {s1_codeword_in[42]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[44]/Q} .original_name {s1_codeword_in[44]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[68]/Q} .original_name {s1_codeword_in[68]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[66]/Q} .original_name {s1_codeword_in[66]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[4]/Q} .original_name {s1_codeword_in[4]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[26]/Q} .original_name {s1_codeword_in[26]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[34]/Q} .original_name {s1_codeword_in[34]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[35]/Q} .original_name {s1_codeword_in[35]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[54]/Q} .original_name {s1_codeword_in[54]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[69]/Q} .original_name {s1_codeword_in[69]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[38]/Q} .original_name {s1_codeword_in[38]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[62]/Q} .original_name {s1_codeword_in[62]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[21]/Q} .original_name {s1_codeword_in[21]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[29]/Q} .original_name {s1_codeword_in[29]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[12]/Q} .original_name {s1_codeword_in[12]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[31]/Q} .original_name {s1_codeword_in[31]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[27]/Q} .original_name {s1_codeword_in[27]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[43]/Q} .original_name {s1_codeword_in[43]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[70]/Q} .original_name {s1_codeword_in[70]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[55]/Q} .original_name {s1_codeword_in[55]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[13]/Q} .original_name {s1_codeword_in[13]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[25]/Q} .original_name {s1_codeword_in[25]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[52]/Q} .original_name {s1_codeword_in[52]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[48]/Q} .original_name {s1_codeword_in[48]/q}
set_db {pin:ecc_engine/s1_data_reg[45]/Q} .original_name {s1_data[45]/q}
set_db {pin:ecc_engine/s1_data_reg[62]/Q} .original_name {s1_data[62]/q}
set_db {pin:ecc_engine/s1_data_reg[3]/Q} .original_name {s1_data[3]/q}
set_db {pin:ecc_engine/s1_data_reg[35]/Q} .original_name {s1_data[35]/q}
set_db {pin:ecc_engine/s1_data_reg[39]/Q} .original_name {s1_data[39]/q}
set_db {pin:ecc_engine/s1_data_reg[52]/Q} .original_name {s1_data[52]/q}
set_db {pin:ecc_engine/s1_data_reg[21]/Q} .original_name {s1_data[21]/q}
set_db {pin:ecc_engine/s1_data_reg[15]/Q} .original_name {s1_data[15]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[16]/Q} .original_name {s1_codeword_in[16]/q}
set_db {pin:ecc_engine/s1_data_reg[1]/Q} .original_name {s1_data[1]/q}
set_db {pin:ecc_engine/s1_data_reg[26]/Q} .original_name {s1_data[26]/q}
set_db {pin:ecc_engine/s1_data_reg[8]/Q} .original_name {s1_data[8]/q}
set_db {pin:ecc_engine/s1_data_reg[33]/Q} .original_name {s1_data[33]/q}
set_db {pin:ecc_engine/s1_data_reg[51]/Q} .original_name {s1_data[51]/q}
set_db {pin:ecc_engine/s1_data_reg[4]/Q} .original_name {s1_data[4]/q}
set_db {pin:ecc_engine/s1_data_reg[31]/Q} .original_name {s1_data[31]/q}
set_db {pin:ecc_engine/s1_data_reg[47]/Q} .original_name {s1_data[47]/q}
set_db {pin:ecc_engine/s1_data_reg[44]/Q} .original_name {s1_data[44]/q}
set_db {pin:ecc_engine/s1_data_reg[28]/Q} .original_name {s1_data[28]/q}
set_db {pin:ecc_engine/s1_data_reg[59]/Q} .original_name {s1_data[59]/q}
set_db {pin:ecc_engine/s1_data_reg[13]/Q} .original_name {s1_data[13]/q}
set_db {pin:ecc_engine/s1_data_reg[12]/Q} .original_name {s1_data[12]/q}
set_db {pin:ecc_engine/s1_data_reg[38]/Q} .original_name {s1_data[38]/q}
set_db {pin:ecc_engine/s1_data_reg[27]/Q} .original_name {s1_data[27]/q}
set_db {pin:ecc_engine/s1_data_reg[55]/Q} .original_name {s1_data[55]/q}
set_db {pin:ecc_engine/s1_data_reg[7]/Q} .original_name {s1_data[7]/q}
set_db {pin:ecc_engine/s1_data_reg[0]/Q} .original_name {s1_data[0]/q}
set_db {pin:ecc_engine/s1_data_reg[61]/Q} .original_name {s1_data[61]/q}
set_db {pin:ecc_engine/s1_data_reg[49]/Q} .original_name {s1_data[49]/q}
set_db {pin:ecc_engine/s1_data_reg[60]/Q} .original_name {s1_data[60]/q}
set_db {pin:ecc_engine/s1_data_reg[29]/Q} .original_name {s1_data[29]/q}
set_db {pin:ecc_engine/s1_data_reg[50]/Q} .original_name {s1_data[50]/q}
set_db {pin:ecc_engine/s1_data_reg[5]/Q} .original_name {s1_data[5]/q}
set_db pin:ecc_engine/s1_valid_reg/Q .original_name {s1_valid/q}
set_db {pin:ecc_engine/s1_data_reg[20]/Q} .original_name {s1_data[20]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[59]/Q} .original_name {s1_codeword_in[59]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[5]/Q} .original_name {s1_codeword_in[5]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[30]/Q} .original_name {s1_codeword_in[30]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[10]/Q} .original_name {s1_codeword_in[10]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[37]/Q} .original_name {s1_codeword_in[37]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[36]/Q} .original_name {s1_codeword_in[36]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[60]/Q} .original_name {s1_codeword_in[60]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[39]/Q} .original_name {s1_codeword_in[39]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[7]/Q} .original_name {s1_codeword_in[7]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[61]/Q} .original_name {s1_codeword_in[61]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[65]/Q} .original_name {s1_codeword_in[65]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[22]/Q} .original_name {s1_codeword_in[22]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[51]/Q} .original_name {s1_codeword_in[51]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[45]/Q} .original_name {s1_codeword_in[45]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[40]/Q} .original_name {s1_codeword_in[40]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[2]/Q} .original_name {s1_codeword_in[2]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[32]/Q} .original_name {s1_codeword_in[32]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[63]/Q} .original_name {s1_codeword_in[63]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[50]/Q} .original_name {s1_codeword_in[50]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[57]/Q} .original_name {s1_codeword_in[57]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[67]/Q} .original_name {s1_codeword_in[67]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[8]/Q} .original_name {s1_codeword_in[8]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[71]/Q} .original_name {s1_codeword_in[71]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[23]/Q} .original_name {s1_codeword_in[23]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[58]/Q} .original_name {s1_codeword_in[58]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[11]/Q} .original_name {s1_codeword_in[11]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[20]/Q} .original_name {s1_codeword_in[20]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[46]/Q} .original_name {s1_codeword_in[46]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[18]/Q} .original_name {s1_codeword_in[18]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[64]/Q} .original_name {s1_codeword_in[64]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[14]/Q} .original_name {s1_codeword_in[14]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[24]/Q} .original_name {s1_codeword_in[24]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[47]/Q} .original_name {s1_codeword_in[47]/q}
set_db {pin:ecc_engine/s1_codeword_in_reg[15]/Q} .original_name {s1_codeword_in[15]/q}
